os: Visual Studio 2017
clone_depth: 1
deploy: off

assembly_info:
    assembly_informational_version: "{version} - CI (AppVeyor, branch: {branch})"

configuration:
    - Debug
    - Release

init:
  - git config --global core.autocrlf true

before_build:
  - dotnet restore

build_script:
  - dotnet build -c %CONFIGURATION% "Decorator\Decorator.csproj"
  
test_script:
  - nuget install OpenCover -Version 4.6.519 -OutputDirecotry packages
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user "-target:%ProgramFiles%\dotnet\dotnet.exe" "-targetargs:test Decorator.Tests\Decorator.Tests.csproj" -returntargetcode "-filter:+[Decorator]*" -hideskipped:All -output:./coverage.xml -oldStyle
  - ps: curl -s https://codecov.io/bash > codecov
  - ps: ./codecov -f .\coverage.xml

artifacts:
 - path: 'Decorator\bin\%CONFIGURATION%\*.nupkg'
   name: Decorator.zip
   